### ISSUE TITLE
Port to Firefox & dont require placeId

### ISSUE THREAD

**Issue by Romvnly-Gaming** [DevKurka/RobloxURLLauncher#1]
Porting to FireFox is easy, I'm sure it won't take too much long, so it'd be nice if you could. 

Also on pages like  **this**: https://www.roblox.com/games/892424128/Jedi-Temple-on-Ilum-UPDATE?gameId=90985f58-0d70-4a0b-b7ed-f7da4919bc0d

you don't need the placeId URL param as it's given natively by roblox, Using a single regex expression would be very nice.

but hey, this is just a `<enhancement>` issue 🏷️

**Comment by DevKurka** [comment]
Thanks for the suggestion. I'll take a look into firefox integration whenever I have a chance to install it.

**Comment by DevKurka** [comment]
@Romvnly-Gaming Added support for mentioned links in 1.8 version. I've also published the extension to firefox webstore, will still have to install firefox and check it out when it passes checks.

**Comment by DevKurka** [comment]
https://addons.mozilla.org/pl/firefox/addon/roblox-url-launcher/

**Comment by Romvnly-Gaming** [comment]
**THANK YOU YOUR AMAZING**

**Comment by DevKurka** [comment]
No problem! You're welcome.

Reopening the issue to still have the firefox version in mind. Will close after I verify it's working. 😉

**Comment by DevKurka** [comment]
@Romvnly-Gaming Hey!

The extension has been just approved @ Firefox. Are you able to confirm if it works properly there?

Link: https://addons.mozilla.org/pl/android/addon/roblox-url-launcher/

**Comment by Romvnly-Gaming** [comment]
![firefox_XWZVSorbX1](https://user-images.githubusercontent.com/62443489/93877431-6fe0de00-fca6-11ea-9f00-3fd726178a49.png)

It doesn't look like it.

**Comment by Romvnly-Gaming** [comment]
Oh wait, I checked again and it works. Sorry!

**Comment by DevKurka** [comment]
So to confirm, running a game via firefox fully works? 😄

**Comment by DevKurka** [comment]
You were probably seeing this error, because Ive posted the android url.

Here's the correct one: https://addons.mozilla.org/addon/roblox-url-launcher/

**Comment by Romvnly-Gaming** [comment]
Yep, looks all good. I just launched the game without the ?placeId param. Thanks so much!

Also just a quick question, is the extension meant to only work when you open a new tab and enter the url?

**Comment by DevKurka** [comment]
It should work as a hyperling as well (if posted on Discord etc.)

Unless what exactly you mean by that? Ran into any specific issue?

**Comment by Romvnly-Gaming** [comment]
Well, unless I open a new tab and the link it doesn't work. 


https://romvnly.xyz/ss/wMHFyyRy.gif

**Comment by DevKurka** [comment]
Ill take a look thanks.

Does the other link type https://www.roblox.com/home?placeId=&gameId= bug as well?

**Comment by Romvnly-Gaming** [comment]
Still works fine, just tested.

**Comment by Romvnly-Gaming** [comment]
Just checking up on this **issue**.

**Comment by DevKurka** [comment]
@Romvnly-Gaming Hey! I remember about it, I just have bunch of things on my head rn. Are you able to send here the link which causes the issue when using as hyperlink?

**Comment by Romvnly-Gaming** [comment]
Yes I can. Here is the [link](https://www.roblox.com/games/892424128/Jedi-Temple-on-Ilum-UPDATE?gameId=5a74a017-a98e-4aa1-9fe4-e31cb129ce6e)

**Comment by Romvnly-Gaming** [comment]
Hi! Just checking up on this issue.

**Comment by DevKurka** [comment]
@Romvnly-Gaming Apologies for delay with that. I've taken a look into it and it seems that Roblox's function loading are delayed on filezilla (or it's just too fast?). Will add an error catching and see if it helps!

**Comment by Romvnly-Gaming** [comment]
That's amazing! Thank you!

**Comment by DevKurka** [comment]
Hopefully v1.9 patches that. I'll let you know when the firefox approves the update.

**Comment by DevKurka** [comment]
@Romvnly-Gaming Seems the update has been approved. Are you able to check if the issue persists?

**Comment by Romvnly-Gaming** [comment]
Yes, I will.

**Comment by Romvnly-Gaming** [comment]
Yep, it seems to work very nicely now even if the tab is not newly created. Thanks!

**Comment by DevKurka** [comment]
Sweet! Thanks!
