### ISSUE TITLE
Games open automatically.

### ISSUE THREAD

**Issue by throwaway1243743852** [DevKurka/RobloxURLLauncher#5]
Any game I click on on the roblox website opens immediately not allowing me to browse servers or look for smaller ones. Also can't use private servers.

**Comment by DevKurka** [comment]
Would you be able to capture a video showing the issue?

I use the extension myself and it doesn't run the game unless an appropriate link is opened.

**Comment by throwaway1243743852** [comment]
https://user-images.githubusercontent.com/107886055/177650608-bbec9030-c29e-4d84-a5fa-8333b02bfad7.mp4

**Comment by DevKurka** [comment]
Hey!

Thanks for a quick follow-up. I see what the problem is. Would you be able to update me with a link that is opened on clicking game icon? (Right click + copy link and paste it here so I can see what the parameters are)

**Comment by throwaway1243743852** [comment]
https://www.roblox.com/games/537413528/Build-A-Boat-For-Treasure?gameSetTypeId=100000003&homePageSessionInfo=2ba34878-ea6b-452a-ac98-a57aeff9f485&numberOfLoadedTiles=1&page=homePage&placeId=537413528&position=0&sortPos=0&universeId=210851291

**Comment by DevKurka** [comment]
Hey @throwaway1243743852 
A potential patch has been published to both Firefox and Google store. Please let me know whether the issue is still happening.

**Comment by throwaway1243743852** [comment]
It is working now

**Comment by DevKurka** [comment]
Thanks for confirmation!
