### ISSUE TITLE
roblox private server  id?

### ISSUE THREAD

**Issue by daud233** [DevKurka/RobloxURLLauncher#6]
where to get roblox private server id?

**Comment by Etheroit** [comment]
Hi!

Apologies for late response. Not sure if it still works but it has to be retrieved by using Roblox API.
( https://games.roblox.com/v1/games/{game-id}/private-servers )
Iirc it used to be retrievable by inspecting element on the private server's "Join" button but it doesn't seem to be anymore therefore you need to either use the api or use network tab in debugger, look for a call to this api endpoint and read the value from the response.

Private server id should be the "accessCode" property.
![image](https://github.com/dv8-studio/RobloxURLLauncher/assets/42714242/4075b9e3-98ae-403b-aefb-e729f8781dc5)
